networks:
  web:
    external: true
services:
  db:
    container_name: db_dobleJ
    environment:
      MYSQL_DATABASE: db_dobleJ_prod
      MYSQL_PASSWORD: lanek2023
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: admin
    image: mysql:latest
    networks:
    - web
    ports:
    - 3307:3306
    volumes:
    - ./data:/var/lib/mysql
version: '3.8'
